name: 'Check PR'

on:
  pull_request:
  workflow_dispatch:

jobs:
  check_renovate_matches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v36.0.0
        with:
          token: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
          configurationFile: '.github/renovate.json5'
        env:
          LOG_FILE: 'renovate.log'
          LOG_FILE_LEVEL: 'info'
          RENOVATE_DRY_RUN: 'extract'
      - name: 'Check Renovate can match dependencies of all descriptors'
        run: .github/scripts/check_renovate_matches.py renovate.log > check_output.log
      - name: 'Build helpful PR comment'
        if: ${{ github.event.pull_request && job.status == 'failure' }}
        run: |
          echo -e 'The following aren't matched by any Renovate manager:\n\n```' > comment.md
          cat check_output.log > comment.md
          echo -e '```\n'
      - name: Find existing comment
        uses: peter-evans/find-comment@v2
        if: ${{ github.event.pull_request && job.status == 'failure' }}
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Generated API diff'
      - name: Create or update diff comment
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ github.event.pull_request && job.status == 'failure' }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          body-file: 'comment.md'
          edit-mode: replace
