name: 'Check PR'

on:
  pull_request:

jobs:
  ci-logic-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install json5
      - run: python3 -m unittest discover -s .github/scripts
