name: 'Check PR'

on:
  pull_request:

jobs:
  ci-logic-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Run unit tests'
        run: python3 -m unittest discover -s .github/scripts
